### ISSUE TITLE
Add inputId property to ng2-completer component (analogy to existing inputName property)

### ISSUE THREAD

**Issue by grubinic** [oferh/ng2-completer#128]
It would be nice to be able to set the id of the input element in ng2-completer component.
I would like to use the id on the html label element for standard label behavior (input focused on label click).

**Comment by szh** [comment]
Any plans to add this feature? As of now, all the fields on my form work well with labels (i.e., clicking the label focuses the input), except for the completer.

**Comment by oferh** [comment]
Should be a simple addition, I'll add it in the next version

**Comment by szh** [comment]
I can confirm that this works. Thanks @oferh!

The only issue is that if I pass a number instead of a string, for instance if I'm databinding using `[inputId]="myVar"` where `myVar` is a number, it doesn't get set (`inputId.length` will be undefined [here](https://github.com/oferh/ng2-completer/commit/054a2543d95d4f64e112052aeef8c5ee69437ecd#diff-1220d22e5c08c8859262c4ccdcc68194R27))
I work around this by binding to `myVar.toString()`.

**Comment by oferh** [comment]
@szh Thanks!
yes `id` must be a string.
