### ISSUE TITLE
Clear selection when search changes

### ISSUE THREAD

**Issue by jairoGilC** [oferh/ng2-completer#45]
Is possible implement a `clearSelected` that clear the input if the content don't match with any value in the list of options

**Comment by oferh** [comment]
You mean to clear it if focus is lost or that the user press tab?

**Comment by jairoGilC** [comment]
yes clear the input when lose the focus if not select any option.

**Comment by supriya2992** [comment]
If no value is selected from the dropdown for the first time then the value of field is blank **but** 
if we select something and then delete the text in ng2-completer, the selected value still remains. Any idea how to clear that value?

**Comment by oferh** [comment]
@supriya2992 I think that the general rule should be that if the input text changes the selected (and model) value should be cleared

**Comment by supriya2992** [comment]
@ofreh not only when selected input changes. I have following scenario:
ng2-completer is a required component. Initially the component is in pristine state.
I want to display an error message "Field is required " when ng2-completer is in dirty state (i.e user has selected some option and value is assigned to model) and  knowingly or unknowingly, user clears the text selected from dropdown. Since the value is not cleared, the errors.required condition of angular 2 becomes false  (i.e. component has a value) and error message is not displayed. 

Here is my code snippet for your reference:
<ng2-completer name="nationality" [dataService]="dataService1" [minSearchLength]="0"  ngModel
   #nationality="ngModel" **required**>
 </ng2-completer>
            
            pristine state {{ nationality.pristine }}
            value {{ nationality.value }} 

 
  <div *ngIf="!nationality.pristine && **nationality.errors** && **notionality.errors.required**>
      <span class="error-msg"> Nationality is required </span>
  </div>

Please feel free to ask me anything else you need to know.

**Comment by oferh** [comment]
fixed in ver 0.2.3

**Comment by gaim281** [comment]
hi ofer,
this does not solves the need, or i just cant find a way to do it.
when a value selected, event 'selected' fired and i bind selected value to my model.
if i go to back the autocomplete box again, and use backspace or ctrl(a)+del and leave the box (with mouse, tab ,etc...), no event is fired so i can update my model and set the value to null.
there is a way forward but no backwards.
even the clearUnselected property sets 'selected' value to null, there is no way to know it when value changed and unselected .
should be also: when value changed and unselected and box becomes blur :fire event onUnselected so model value can be reset.
thanks for your time dude...
